version: "3.3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: friendlyhello
    environment:
      NAME: hello
#    env_file:
#      - ./a.env
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - webnet
  redis:
    image: redis
#    ports:
#      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - webnet
networks:
  webnet:
